@MethodsReturnNonnullByDefault
@ParametersAreNonnullByDefault
package xyz.brckts.portablestonecutter.compat.jei;

import net.minecraft.MethodsReturnNonnullByDefault;

import javax.annotation.ParametersAreNonnullByDefault;